CT-859 Cache builded images
keboola/storage-backend pull request #112
Opened 2023-10-30 09:15 UTC by tomasfejfar

2023-10-30 12:22 UTC, zajca requested changes
No vidím, že je tam upload do ECR, ale nevidím, že by sa ten image pak stahoval. Protože všude je pak pořád `actions/download-artifact` něco sem přehlédl?

2023-10-30 12:23 UTC, tomasfejfar commented
Ježiš, tyvole to jsem dement, já jsem to špatně resetnul, když jsem odděloval od sebe tenhle image a images těch jednotlivých věcí pak :( Díky ❤️

2023-10-30 15:13 UTC, tomasfejfar commented
Už je to zpátky :)

2023-10-30 16:13 UTC, tomasfejfar commented
Tady je build kde to proběhne

2023-10-31 08:01 UTC, zajca approved these changes
:heavy_check_mark:

2023-10-31 10:48 UTC, tomasfejfar commented
Rebase and squash.

2023-10-31 11:35 UTC, merged