CT-1118 null value for import
keboola/storage-backend pull request #136
Opened 2024-03-12 09:42 UTC by zajca

Jira: CT-1118
Connection PR: XXX
SAPI PR: XXX

---

2024-03-12 14:38 UTC, zajca commented on packages/php-db-import-export/src/Backend/Bigquery/ToStage/FromGCSCopyIntoAdapter.php
> +        }
docela zajímavá věc nepodařilo sa mě ten null marker nijak zrušit. Default je to empty string. Nejde nastavit na nic, při nastavení na null dělá default, když sa nepošle tak dělá default :)

2024-03-14 00:00 UTC, jirkasemmler requested changes
bal jsem se toho, ale nevypada to tak zle

2024-03-14 00:00 UTC, jirkasemmler commented on packages/php-db-import-export/tests/functional/Snowflake/ToStage/StageImportFileTest.php
> +                importAsNull: ['3', '2'], // two values are passed second is ignored
```suggestion
                importAsNull: ['3', '2'], // two values are passed, both of them applied
```

2024-03-14 08:23 UTC, zajca commented on packages/php-db-import-export/src/Backend/Snowflake/SnowflakeImportOptions.php
> +    public function getNullIfSql(): string
přidal sem

2024-03-14 14:13 UTC, jirkasemmler approved these changes

2024-03-14 14:14 UTC, merged