Release and split monorepi
keboola/storage-backend pull request #52
Opened 2023-03-05 17:33 UTC by romanbracinik

Pridavam finalnu fazu kde je mozne po merge v GH spustit rucny release a repo si vytvori svoje tagy pre kazdy repozitar a split script by sa mal postarat o ostatne

2023-03-05 17:39 UTC, romanbracinik commented on monorepo-builder.php
>  //        PushTagReleaseWorker::class,
Po review a mergi toto odkomentujem

2023-03-06 08:57 UTC, romanbracinik commented on monorepo-builder.php
>  //        PushNextDevReleaseWorker::class,
Toto odstranim

2023-03-06 13:47 UTC, tomasfejfar requested changes

2023-03-06 13:47 UTC, tomasfejfar commented on src/AddTagPerPackagesWorker.php
> +        $directories = glob('/code/packages/*' , GLOB_ONLYDIR);
Aby to sedělo s tím, s čím počítá ten monorepo builder

2023-03-06 13:47 UTC, tomasfejfar commented on src/AddTagPerPackagesWorker.php
> +        $directories = glob('/code/packages/*' , GLOB_ONLYDIR);
\Symplify\MonorepoBuilder\Package\PackageProvider::provide

2023-03-06 13:50 UTC, romanbracinik commented on src/AddTagPerPackagesWorker.php
> +        $directories = glob('/code/packages/*' , GLOB_ONLYDIR);
No skusim to este pozriet, ale problem tam bol ze on to berie priamo z toho composer.json co je napr v pripade ie libky "name": "keboola/db-import-export", ale vlastne ten tag ma byt `php-db-import-export` takze by bolo potreba premenovat ten balicek :) preto to mam tu podla toho dir name

2023-03-06 13:56 UTC, tomasfejfar commented on src/AddTagPerPackagesWorker.php
> +        $directories = glob('/code/packages/*' , GLOB_ONLYDIR);
Můžeš si vytahnout ty composer file a na nich zavolat basepath. Spíš jde o to, aby to fungovalo s exclude třeba... aby to bylo stejně jako v \Symplify\MonorepoBuilder\Finder\PackageComposerFinder::getPackageComposerFiles

2023-03-06 13:57 UTC, romanbracinik commented on src/AddTagPerPackagesWorker.php
> +        $directories = glob('/code/packages/*' , GLOB_ONLYDIR);
Jo tak jasne :) ok upravim to 👍

2023-03-06 13:57 UTC, tomasfejfar commented on src/AddTagPerPackagesWorker.php
> +        $directories = glob('/code/packages/*' , GLOB_ONLYDIR);
Ale přijde mi zmatčné do budoucna, že to nezávisí na té samé věci jako zbytek toho monorepo builderu

2023-03-06 13:58 UTC, romanbracinik commented on src/AddTagPerPackagesWorker.php
> +        $directories = glob('/code/packages/*' , GLOB_ONLYDIR);
No tie nazvy tagov by som teda bud nechal tak ako to je, alebo ak by sme to mali menit tak by som uz asi bol skor za upravit ten split script ze by som mudal len verziu a on by to rozstrielal do ostatnych repozitarov

2023-03-06 13:58 UTC, tomasfejfar commented on src/AddTagPerPackagesWorker.php
> +        $directories = glob('/code/packages/*' , GLOB_ONLYDIR);
Plus je třeba ještě \Symplify\MonorepoBuilder\Command\PackagesJsonCommand

2023-03-07 18:30 UTC, romanbracinik commented on src/AddTagPerPackagesWorker.php
> +        $directories = glob('/code/packages/*' , GLOB_ONLYDIR);
Tak upravil som to a vsimol som si ze sa nam tam vlastne includovala vec co sme uplne nechceli v `db-import-export` ma este composer provisioning tak som to rovno hodil do exclude a pouzil to v tom commande

2023-03-08 06:15 UTC, romanbracinik commented
Doplnim este to readme

2023-03-08 10:34 UTC, tomasfejfar approved these changes
Jo funguje mi to

2023-03-08 11:30 UTC, merged