CT-1055 assertSameColumns length
keboola/storage-backend pull request #71
Opened 2023-05-26 11:19 UTC by zajca

JIRA: CT-1055

2023-05-29 07:39 UTC, zajca commented
Poslední commit opravuje testMoveDataFromAToBRequireSameTablesFailColumnMismatch ten jediný spadnul https://github.com/keboola/storage-backend/actions/runs/5090244576/jobs/9149254833?pr=71

2023-05-29 07:41 UTC, zajca commented on packages/php-db-import-export/src/Backend/Assert.php
> +        array $complexLengthTypes = [],
Místo assertu per backend sem přidal možnost přidat vlastní typy kde sa bude jinak porovnávat length tím je to univerzální a pro ostatní backendy stačí vypsat datové typy.

2023-05-31 07:41 UTC, zajca commented
Udělal sem rebase nad main.

2023-05-31 08:22 UTC, jirkasemmler requested changes
trochu bych to dovysvetlil, protoze to umi uvarit hlavu. A trochu se bojim az v battle testingu se potkame treba s Teradati `INTERVAL YEAR [(n)] TO MONTH` ale to je hudba daleke (spis nerealne) budocnosti

2023-05-31 08:22 UTC, jirkasemmler commented on packages/php-db-import-export/src/Backend/Assert.php
> +        return $sourcePrecision > $destinationPrecision || $sourceScale > $destinationScale;
nechces to pretypovat na int?

2023-05-31 08:22 UTC, jirkasemmler commented on packages/php-db-import-export/src/Backend/Assert.php
> +     * @param string[] $complexLengthTypes
```suggestion
     * @param string[] $complexLengthTypes - list of numeric types where length is presented by <scale:int>,<precision:int>
```

2023-05-31 08:24 UTC, zajca commented on packages/php-db-import-export/src/Backend/Assert.php
> +    /**
No toto není pravda, je to pravda enom když tam dáš ty typy, které chceš aby sa takto chovali a tady to chování bys měl ověřit v testu.

2023-05-31 08:36 UTC, zajca commented on packages/php-db-import-export/src/Backend/Assert.php
> +    /**
krapet sem to přeformuloval

2023-05-31 08:42 UTC, jirkasemmler approved these changes

2023-05-31 11:02 UTC, merged