Big 126 external buckets
keboola/storage-backend pull request #82
Opened 2023-08-29 15:32 UTC by romanbracinik

JIRA: big-126

Upravujem to kvoli BQ https://github.com/keboola/php-storage-driver-bigquery/pull/48
Ked to bude mergnute poslem PR na upravu TD, ta sice nepodporuje branchovanu storage, tak to tam osetrim ze to branch id nieje vyplnene. 

Pridavat to do meta mi prisla horsia varianta.

2023-08-30 07:01 UTC, zajca reviewed
K čemu je ti to branchId? Nenapadá mě co bys stím na tom backendu dělal.

2023-08-30 07:03 UTC, romanbracinik commented
> K čemu je ti to branchId? Nenapadá mě co bys stím na tom backendu dělal.

U BQ to funguje tak, ze sa ten dataset linkne do projektu, takze fyzicky ten objekt vytvorim (linknem) v BQ projektu takze musi mat prefix branche v pripade tak aby to bolo zhodne s tim ako funguju buckety imho

2023-08-31 07:55 UTC, romanbracinik commented
Pridal som teda este ten response co bude potreba

2023-08-31 08:51 UTC, zajca requested changes
Nemožeš měnit ten int ten má vliv na to jak sa ten objekt serializuje/deserializuje takto je to BC. Sice to teď nepoužíváme v api přímo, ale bude lepší sa toho držat.

2023-08-31 08:51 UTC, zajca commented on packages/php-storage-driver-common/proto/bucket.proto
> +  google.protobuf.Any meta = 4;
takto ne, nemožeš měnit ty čísla meta musí ostat 3 a branchId bude 4

2023-08-31 08:51 UTC, zajca commented on packages/php-storage-driver-common/proto/bucket.proto
> +  google.protobuf.Any meta = 5; // metadata specific for each backend
stejně tak takdy to čílso musí ostat stejné.

2023-08-31 11:02 UTC, romanbracinik commented
diky @zajca to som nevedel

2023-08-31 11:04 UTC, zajca approved these changes

2023-08-31 12:56 UTC, merged